project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-line-numbers: true
    grid:
      sidebar-width: 200px
      body-width: 1050px
      margin-width: 200px
      gutter-width: 1rem

website:
  twitter-card:
     creator: "@eliasdabbas"
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - text: ""
        href: /
    tools:
      - icon: twitter
        href: https://twitter.com/eliasdabbas
        text: EliasDabbas Twitter
      - icon: linkedin
        href: https://linkedin.com/in/eliasdabbas
        text: EliasDabbas LinkedIn
      - icon: github
        href: https://github.com/eliasdabbas/adviz
        text: adviz Github

  sidebar:
    style: floating
  google-analytics: "G-N2M6ZCQTX5"

metadata-files: [nbdev.yml, sidebar.yml]
